# Generated by Django 3.1.6 on 2021-02-15 16:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField()),
                ('is_video', models.BooleanField(default=False)),
                ('likes', models.JSONField(blank=True)),
                ('comments', models.JSONField(blank=True)),
                ('date', models.DateField(verbose_name=datetime.datetime(2021, 2, 15, 16, 38, 27, 400432))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', related_query_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
