# Generated by Django 3.1.6 on 2021-02-15 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210215_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 15, 16, 41, 37, 837854)),
        ),
    ]
