# Generated by Django 3.1.6 on 2021-02-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_url',
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
