# Generated by Django 3.2.7 on 2021-09-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210926_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow_request',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
