# Generated by Django 3.2.7 on 2021-09-25 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_follow_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='_profile_picture',
        ),
    ]
