# Generated by Django 3.2.7 on 2021-09-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_profile_picture_profile__profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='_profile_picture',
            new_name='profile_picture',
        ),
    ]
